In [ ]:
import numpy as np
arr1=np.array([[1,2,3],[3,4,5]])
arr2=np.array([[5,6,7],[7,8,0]])
print(arr1,arr2,sep="\n")

[[1 2 3]
 [3 4 5]]
[[5 6 7]
 [7 8 0]]


In [ ]:
print("Addition :\n",np.add(arr1,arr2))
print("Subtraction \n",np.subtract(arr1,arr2))
print("Multiplication \n",np.multiply(arr1,arr2))
print("Division \n",np.divide(arr1,arr2))

Addition :
 [[ 6  8 10]
 [10 12  5]]
Subtraction 
 [[-4 -4 -4]
 [-4 -4  5]]
Multiplication 
 [[ 5 12 21]
 [21 32  0]]
Division 
 [[0.2        0.33333333 0.42857143]
 [0.42857143 0.5               inf]]


/tmp/ipython-input-1712915949.py:4: RuntimeWarning: divide by zero encountered in divide
  print("Division \n",np.divide(arr1,arr2))


In [ ]:
arr1=[[1,2],[3,4]]
arr2=[[6,8],[9,10]]
print(np.dot(arr1,arr2))

[[24 28]
 [54 64]]


# Create a python script takes user i/p for name and marks .Writes into a file and display all entries

In [ ]:
import csv
n=int(input("Enter number of inputs  :"))
with open("file_cls.csv","w",newline="") as f:
    wr=csv.writer(f)
    wr.writerow(["Name","Marks"])
    for i in range(n):
      a=input("Enter name  :")
      b=int(input("Enter marks  :"))
      wr.writerow([a,b])
with open("file_cls.csv","r",newline="") as f:
    r=csv.reader(f)
    for i in r:
      print(i)

Enter number of inputs3
Enter name  :Srikar
Enter marks  :19
Enter name  :abhi
Enter marks  :15
Enter name  :banda 
Enter marks  :20
['Name', 'Marks']
['Srikar', '19']
['abhi', '15']
['banda ', '20']
